### ISSUE TITLE
The complete function is not executing

### ISSUE THREAD

**Issue by omar1893** [andela-jkithome/vue-todo#1]
The complete function is not executing i dont know why... i put a couple of console logs and they dont get executed... i checked the whole .vue looking for an error and i still dont solve it

**Comment by jkithome** [comment]
@omar1893 Could you give me a link to your work so I can take a look?

**Comment by omar1893** [comment]
Sure here its the repo:

**Comment by omar1893** [comment]
https://github.com/omar1893/vue-todoApp

**Comment by jkithome** [comment]
@omar1893 Found the issue and opened up a PR.
